export const PUZZLES = 'PUZZLES';
export const MATRICES = 'MATRICES';
export const PUZZLE_STATES = 'PUZZLE_STATES';
export const PUZZLES_CURRENT_STATES = 'PUZZLES_CURRENT_STATES';
export const LEVELS = 'LEVELS';
export const GAME_INDICATORS = 'GAME_INDICATORS';
export const GAME_METRICS = 'GAME_METRICS';
export const SETTINGS = 'SETTINGS';
export const MARKETING_INDICATORS = 'MARKETING_INDICATORS';
export const MARKETING_METRICS = 'MARKETING_METRICS';

export const SCENARIO_DESCRIPTION = 'SCENARIO_DESCRIPTION';
